theme = "dracula"

[editor]
line-number = "absolute"
mouse = true
shell = ["zsh", "-c"]
scrolloff = 10
rulers = [121]
cursorline = true
color-modes = true
bufferline = "always"
auto-format = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.lsp]
display-messages = true

# sub word movement keybinds
[keys.normal]
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'

[keys.select]
W = 'extend_next_sub_word_start'
B = 'extend_prev_sub_word_start'
E = 'extend_next_sub_word_end'
