theme = "gruvbox"

[editor]
line-number = "absolute"
mouse = true
shell = ["zsh", "-c"]
scrolloff = 20
rulers = [121]
cursorline = true
color-modes = true
bufferline = "always"
auto-format = false

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.lsp]
display-messages = true
